### ISSUE TITLE
Adding of status

### ISSUE THREAD

**Issue by Emmanuel-Etukudo** [zurichat/zc_app#259]
As a user, I want to also be able to add my status.

**Comment by Olaoluwa1995** [comment]
Link for testing: https://appetize.io/app/q2mdgj7wdv5ujuh71ygj0kpja0?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

Procedures for Testing: 
- Run the application
- Scroll up to see the remaining content on the screen

https://user-images.githubusercontent.com/58240682/132044801-fed20e51-fb9a-43f3-a55c-123716c8ae46.mp4
