### ISSUE TITLE
Search through my channels

### ISSUE THREAD

**Issue by Emery-hub** [zurichat/zc_app#267]

**Comment by DestinyOgbonna** [comment]
This request Solves issue #267 .

https://appetize.io/app/ftk8j6h6v1qw28zb2jc6dxt6cm?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

https://user-images.githubusercontent.com/80477923/132130313-ffda8bb6-1cc0-4379-8241-841aa8a1d22f.mp4
