### ISSUE TITLE
Create home screen

### ISSUE THREAD

**Issue by Quwaysim** [zurichat/zc_app#374]
As a user, I want to be able to view my threads, channels and DMs on my home screen

**Comment by oluwadamme** [comment]
i implemented the Home screen UI of the Zuri chat app
Testing link: [Home Screen
![Screenshot_20210902-222430](https://user-images.githubusercontent.com/41980829/131918471-6b1cc58c-c5e6-429a-ab10-d219bbe22970.jpg)
](https://appetize.io/app/j7d7056hm4n6dgur4nrq4ky6zr?device=pixel4&scale=75&orientation=portrait&osVersion=10.0)

**Comment by oluwadamme** [comment]
https://appetize.io/app/kcgvdxp9h4608ajnc049fk15b8?device=pixel4&scale=75&orientation=portrait&osVersion=10.0
