### ISSUE TITLE
Look up (other) users by their username, to chat with them

### ISSUE THREAD

**Issue by Detective-Khalifah** [zurichat/zc_app#385]
I'd like search up users by their username, so I can chat with them, even if they're not part of my contacts, or users I've directly messaged prior.
1.  Tap on the search bar
2. Type a username using some notation (like '@') to make this type of search unique, and unlike a search for text in one of my chats, for example.
3. App should list users with exact usernames and/or usernames that are close hits/
4. Option to add/save and/or chat with found user.

**Comment by Tobilohba** [comment]
https://www.figma.com/file/tzZk3pGdPrSxhRcLk86DAD/Abd_Salam-Issue-design?node-id=2%3A662

**Comment by imfaith-hq** [comment]
Resolving Issue #385 
**### A DM jump page to search for users and channels and to open up chat with the, DM jump to screen**

Here is the link to the app hosted on appetizer FOR TESTING........       https://appetize.io/app/kjd499gc51xhhruwpkvj8hvuqm
                                                                          #############      [https://appetize.io/app/kjd499gc51xhhruwpkvj8hvuqm](url)

PROCEDURES FOR TESTING
* Run the Application
* Swipe Up and down to see the list of Recent Channels and dms opened
* Type in the Search Bar to Locate a User or Channel
* Swipe across the screen on top of the possible list of users your searching for



![faith](https://user-images.githubusercontent.com/59166014/132134995-34803a25-e3ff-4282-b211-4fb1d2c2bc5d.gif)



https://user-images.githubusercontent.com/59166014/132135188-252ed2bb-bf68-4354-a6dc-ef8bf7f50995.mp4
