### ISSUE TITLE
Profile popup on long click

### ISSUE THREAD

**Issue by ugoostanleyibe** [zurichat/zc_app#458]
A user should be able to see a popup of another user’s profile when they hover or long click on the other user's username

**Comment by thisispascal** [comment]
A user should be able to see a popup of another user’s profile when they hover or long click on the other user's username

Link to testing: https://appetize.io/app/ve6crkkzjehh2ax9rakg0mp254?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

Procedure for testing:
-Run the application.
-Scroll to the 'Direct Messages' section.
-Long-press any of the usernames.
-The user's profile should pop up.
-Dismiss by tapping anywhere on the screen.

This confirms that a user can see a popup of another user’s profile when they long click on the other user's username

https://user-images.githubusercontent.com/89068753/132102655-9947bdd1-55ec-463e-96f1-9accd29f433a.mp4
