### ISSUE TITLE
Setup CI/CD using Github Actions in the repo with Github workflow

### ISSUE THREAD

**Issue by Arch997** [zurichat/zc_app#505]

**Comment by Detective-Khalifah** [comment]
[] Trigger on every PR.
[] Should run flutter test and comment on the repo.
[] Should build the apk for release on every new tag.

**Comment by demolaf** [comment]
- [ ] Trigger on every PR.
- [ ] Should run flutter test and comment on the repo.
- [ ] Should build the apk for release on every new tag.

**Comment by pauleke65** [comment]
I've create a GitHub Action Workflow that:
* Triggers on every PR.
* Runs flutter test and comments on the repo.
* Builds the apk for release

**Comment by pauleke65** [comment]
Successfully implemented workflows that does the following:

Link to PR: https://github.com/zurichat/zc_app/pull/540

- [x] Trigger on every PR(to the dev branch).
- [x] Should run flutter test and comment on the repo.
- [x] Should build the apk for release on every new tag.

Below is a video explaining the process and code:

https://user-images.githubusercontent.com/17278452/131819659-cf507e50-11e2-4b3f-89e0-9f2a66527111.mp4


Link to the tests done on my forked repo:
https://github.com/pauleke65/zc_app/actions

**Comment by pauleke65** [comment]
Github has new security policies which was restricting the Github bot from commenting if the PR wasn't from someone with write permissions in the repo. But, the latest commit fixes this by triggering another workflow which has write permissions after the PR workflow is successful.
More about the security issue here: [Preventing PWN requests] (https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

I'm using the recommended solution from github
