### ISSUE TITLE
Setup LocalStorageService for persisting data between app restarts

### ISSUE THREAD

**Issue by Blazebrain** [zurichat/zc_app#535]
As a user, I want to be able to save my data between app restarts

Link to testing: https://appetize.io/app/01maqa9k0b50p27nvh22dca3d0

Procedures for Testing:
- Run the application
- Click the green floating action button at the bottom right to navigate to the testing page.
- Type in any word you wish to save. You will be redirected to the homescreen.
- Click the floating action button again to verify.
- The text typed in earlier would be displayed in the line 'the previous value you entered is: '

This verifies that the user can save a piece of data and get it back for use later, even after restarting the app.

<img src="https://media.giphy.com/media/8ilybTKDleeR3t5YeE/giphy.gif?cid=790b76113730730cd6ce698a0f36356243662c7caf218887&rid=giphy.gif&ct=g" width =200>

**Comment by markessien** [comment]
k
