### ISSUE TITLE
Onboarding screen 

### ISSUE THREAD

**Issue by Yczar** [zurichat/zc_app#63]
As a user, I want to see a screen (screens) that tells me what the app is about and what to do.

**Comment by Detective-Khalifah** [comment]
## Issue Resolved. Refer [this](https://github.com/zurichat/zc_app/pull/586) pull request.

My commits display an onboarding screen of three, as illustrated by the designers of 'team-socrates'
+ Open app
+ Onboarding screen describing app display -- image, title, subtitle
  - Dots appear at the bottom, indicating number of pages
  - Swipe screen left or right to view the screens
  - At the last (third) screen, tap on 'Done' at the bottom-right corner to open the home page of app

https://user-images.githubusercontent.com/58272349/132073671-bca23b54-46ec-4267-a007-e90be0e78c42.mp4

## [Testing Link](https://appetize.io/app/dbn0t008afbx0xc61bttw1wctr)

**Comment by Detective-Khalifah** [comment]
Time to close the issue, @Yczar
