### ISSUE TITLE
Change Language feature

### ISSUE THREAD

**Issue by Raykemzy** [zurichat/zc_app#67]
As a user I want to have an option to change the app default language to my preferred language, so that I can be able to communicate effectively with the application.

**Comment by pappin2010** [comment]
https://www.figma.com/file/eB8ijotpeP4xMyGZmhF2Ez/Change-Language-feature-67?fuid=985168419452224945

**Comment by pappin2010** [comment]
https://www.figma.com/file/eB8ijotpeP4xMyGZmhF2Ez/Change-Language-feature-67?fuid=985168419452224945
